[book]
authors = ["Jan Gosmann"]
language = "en"
src = "src"
title = "btdt - User Guide"

[output.html]
git-repository-url = "https://github.com/jgosmann/btdt"
edit-url-template = "https://github.com/jgosmann/btdt/edit/main/{path}"