name: Build and publish Docker image

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag `btdt-[cli|server]-vX.Y.Z` to build a Docker image for.'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Extract image name and version
        id: version-info
        run: |
          REF=${{ inputs.version || github.event.release.tag_name }};
          TAG=${REF#refs/*/};
          VERSION=${TAG#btdt-*-}
          COMPONENT=${TAG%-v*};
          
          echo "component=${COMPONENT}" >> $GITHUB_OUTPUT
          echo "image_name=${COMPONENT}/btdt-cli/btdt}" >> $GITHUB_OUTPUT
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version || github.event.release.tag_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.version-info.outputs.image_name }}

      - name: Get tags for Docker image
        id: image-tags
        shell: bash
        run: |
          echo 'TAGS<<EOF' >> "$GITHUB_OUTPUT"
          curl  --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" --header "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/jgosmann/btdt/releases \
          | jq --raw-output '.[]["tag_name"] | sub("^v"; "")' \
          | docker run --rm jgosmann/gen-semver-tags:0.1 ${{ steps.version-info.outputs.version }} \
          | awk '{print "${{ steps.version-info.outputs.image_name }}:"$0}' \
          >> "$GITHUB_OUTPUT"
          echo 'EOF' >> "$GITHUB_OUTPUT"

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.image-tags.outputs.TAGS }}
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}